# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vivadolabs/lab6/VGA_interface/xterm/xterm.srcs/sources_1/ip/myclk_wiz/myclk_wiz.xci
# IP: The module: 'myclk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivadolabs/lab6/VGA_interface/xterm/xterm.gen/sources_1/ip/myclk_wiz/myclk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'myclk_wiz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vivadolabs/lab6/VGA_interface/xterm/xterm.gen/sources_1/ip/myclk_wiz/myclk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'myclk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vivadolabs/lab6/VGA_interface/xterm/xterm.gen/sources_1/ip/myclk_wiz/myclk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myclk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Vivadolabs/lab6/VGA_interface/xterm/xterm.srcs/sources_1/ip/myclk_wiz/myclk_wiz.xci
# IP: The module: 'myclk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivadolabs/lab6/VGA_interface/xterm/xterm.gen/sources_1/ip/myclk_wiz/myclk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'myclk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vivadolabs/lab6/VGA_interface/xterm/xterm.gen/sources_1/ip/myclk_wiz/myclk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'myclk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vivadolabs/lab6/VGA_interface/xterm/xterm.gen/sources_1/ip/myclk_wiz/myclk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myclk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
