set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports F]
set_property PACKAGE_PIN J15 [get_ports A]
set_property PACKAGE_PIN J18 [get_ports B]
set_property PACKAGE_PIN H17 [get_ports F]
