# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Vivadolabs/lab6/lab6_pdf_and_resources/lab6/xterm.xdc

# IP: ip/vga_mem/vga_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_mem || ORIG_REF_NAME==vga_mem} -quiet] -quiet
