set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports init]

set_property PACKAGE_PIN J15 [get_ports init]
set_property PACKAGE_PIN J17 [get_ports {O_led[0]}]
set_property PACKAGE_PIN J18 [get_ports {O_led[1]}]
set_property PACKAGE_PIN J14 [get_ports {O_led[3]}]
set_property PACKAGE_PIN P14 [get_ports {O_led[4]}]
set_property PACKAGE_PIN T14 [get_ports {O_led[5]}]
set_property PACKAGE_PIN K2 [get_ports {O_led[6]}]
set_property PACKAGE_PIN U13 [get_ports {O_led[7]}]
set_property PACKAGE_PIN T10 [get_ports {O_seg[0]}]
set_property PACKAGE_PIN R10 [get_ports {O_seg[1]}]
set_property PACKAGE_PIN K16 [get_ports {O_seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {O_seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {O_seg[4]}]
set_property PACKAGE_PIN T11 [get_ports {O_seg[5]}]
set_property PACKAGE_PIN L18 [get_ports {O_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[7]}]

set_property PACKAGE_PIN T9 [get_ports {O_led[2]}]

